AlinWebSystem/Controllers/AgenciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Entities;
using Interfaces;
using Validator.AgenciaValidator;
using DataBase;
using Repository;

namespace AlinWebSystem.Controllers
{
    public class AgenciaController : Controller
    {
        private InterfaceAgencia repoAgencia;
        private InterfaceArea repoAreas;
        private InterfaceDetalleAgencia detalleAgencia;
        private AgenciaValidator validator;

        public AgenciaController(AgenciaRepository repoAgencia, AreaRepository repoAreas, DetalleAgenciaRepository detalleAgencia,AgenciaValidator validator)
        {
            this.repoAgencia = repoAgencia;
            this.repoAreas = repoAreas;
            this.detalleAgencia = detalleAgencia;
            this.validator = validator;
        }

        [HttpGet]
        public ViewResult Index(string criterio = "")
        {
            var datos = repoAgencia.ByQueryAll(criterio);
            return View("Inicio", datos);
        }

        [HttpGet]
        public ViewResult Create()
        {
            ViewBag.Area = repoAreas.AllArea("");
            return View("RegistrarAgencia");

        }

        [HttpPost]
        public ActionResult Create(Agencia agencia)
        {
            //validator.Execute(agencia);
            //validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));

            if (agencia == null)
            {
                agencia = new Agencia();
            }
            if (ModelState.IsValid)
            {
                repoAgencia.Store(agencia);
                TempData["UpdateSuccess"] = "Se Guardo Correctmente";
                return RedirectToAction("Index");
            }
            return View("RegistrarAgencia", agencia);
        }

        [HttpGet]
        public ActionResult Item(int id, int position)
        {
            var model = repoAreas.Find(id);
            ViewBag.Area = position;
            return PartialView("_Item", model);
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            var data = repoAgencia.Find(id);
            ViewBag.Detalle = detalleAgencia.GetDetalleByNro(data.Nombre);
            //ViewBag.Area = repoAreas.All();
            return View("Editar", data);
        }

        [HttpPost]
        public ActionResult Edit(Agencia agencia)
        {
             validator.Execute(agencia);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));
            if (ModelState.IsValid)
                {

                    repoAgencia.Update(agencia);
                    TempData["UpdateSuccess"] = "Se Actualizo correctamente";
                    return RedirectToAction("Index");
                }
            return View("Editar", agencia);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            repoAgencia.Delete(id);
            TempData["UpdateSuccess"] = "Se Elimino correctamente";
            return RedirectToAction("Index");
        }
    }
}

AlinWebSystem/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Interfaces;
using Entities;
using Validator.AreaValidator;
using Repository;

namespace AlinWebSystem.Controllers
{
    public class AreaController : Controller
    {
        private InterfaceArea areaRepository;
         private AreaValidator validator;

         public AreaController(AreaRepository areaRepository, AreaValidator validator)
        {
            this.areaRepository = areaRepository;
            this.validator = validator;
        }

        [HttpGet]
        public ViewResult Index(string query = "")
        {
            var datos = areaRepository.AllArea(query);
            return View("Inicio", datos);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View("RegistrarArea");
        }

        [HttpPost]
        public ActionResult Create(Area area)
        {
            validator.Execute(area);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));

            if (ModelState.IsValid)
            {
                areaRepository.Store(area);
                TempData["UpdateSuccess"] = "Se actualizo correctamente";
                return RedirectToAction("Index");
            }

            return View("RegistrarArea", area);
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            var data = areaRepository.Find(id);
            return View("EditarArea", data);
        }

        [HttpPost]
        public ActionResult Edit(Area area)
        {
            validator.Execute(area);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));
            if (ModelState.IsValid)
            {
                areaRepository.Update(area);
                TempData["UpdateSuccess"] = "Se Actualizo correctamente";
                return RedirectToAction("Index");
            }
             return View("EditarArea", area);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            areaRepository.Delete(id);
            TempData["UpdateSuccess"] = "Se Élimino correctamente";
            return RedirectToAction("Index");
        }
    }
}

AlinWebSystem/Controllers/ModulosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlinWebSystem.Controllers
{
    public class ModulosController : Controller
    {

        public ActionResult Index()
        {
            return View("Inicio");
        }

        public ViewResult Index2()
        {
            return View("InicioAlm");
        }
    }
}

AlinWebSystem/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

//Importamos
using Interfaces;
using Entities;
using Validator.ProveedorValidators;

namespace AlinWebSystem.Controllers
{
    public class ProveedorController : Controller
    {
        private InterfaceProveedor repository;
        private ProveedorValidators validator;

        public ProveedorController(InterfaceProveedor repository, ProveedorValidators validator)
        {
            this.repository = repository;
            this.validator = validator;
        }

        [HttpGet]
        public ViewResult Index(string query = "")
        {
            var datos = repository.ByQueryAll(query);
            return View("ListaProveedores", datos);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View("RegistrarProveedor");
        }

        [HttpPost]
        public ActionResult Create(Proveedor proveedor)
        {
            validator.Execute(proveedor);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));

            if (ModelState.IsValid)
            {
                repository.Store(proveedor);

                TempData["UpdateSuccess"] = "Se Guardo Correctamente";

                return RedirectToAction("Index");
            }

            return View("RegistrarProveedor", proveedor);
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            var data = repository.Find(id);
            return View("EditarProveedor", data);
        }

        [HttpPost]
        public ActionResult Edit(Proveedor proveedor)
        {
            validator.Execute(proveedor);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));
            if (ModelState.IsValid)
            {
                repository.Update(proveedor);
                TempData["UpdateSuccess"] = "Se Actualizó Correctamente";
                return RedirectToAction("Index");
            }
            return View("EditarProveedor",proveedor);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            repository.Delete(id);
            TempData["UpdateSuccess"] = "Se Eliminó Correctamente";
            return RedirectToAction("Index");
        }
    }
}

AlinWebSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>- AlinWebSystem - </title>
    <link rel="shortcut icon" type="image/x-icon" href="Image/favicon.ico" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

     @*Bootstrap Core CSS 
    <link href="/Content/css/bootstrap.min.css" rel="stylesheet">*@

     @*Custom CSS 
    <link href="/Content/css/sb-admin.css" rel="stylesheet">*@

     @*Morris Charts CSS*@ 
    <link href="/Content/css/plugins/morris.css" rel="stylesheet">

    @*Custom Fonts*@ 
    <link href="/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <link href="~/Content/bootstrap.yeti.min.css" rel="stylesheet" />  
    <script src="~/Scripts/jquery-2.2.3.min.js"></script>

</head>
<body>
   
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span><span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AlinWebSystem", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a class="dropdown-togle" data-toggle="dropdown" href="#">
                            Admin. Proveedor
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenuDivider">
                            <li><a href="@Url.Action("Index", "Proveedor")">Buscar Proveedor</a></li>
                            <li><a href="@Url.Action("Create", "Proveedor")">Registrar Proveedor</a></li>
                        </ul>
                    </li>

                    @*   probando el menu*@
                    <li class="dropdown">
                        <a class="dropdown-togle" data-toggle="dropdown" href="#">
                            Administrar
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenuDivider">
                            <li><a href="@Url.Action("Index2", "Modulos")">Almacen</a></li>
                            <li role="presentation" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Modulos")">Inventarios</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-togle" data-toggle="dropdown" href="#">
                            Admin. Agencias
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenuDivider">
                            <li><a href="@Url.Action("Index", "Agencia")">Buscar Agencia</a></li>
                            <li><a href="@Url.Action("Create", "Agencia")">Registrar Agencia</a></li>
                            <li role="presentation" class="divider"></li>
                            <li><a href="@Url.Action("Index","Area")">Buscar Area</a></li>
                            <li><a href="@Url.Action("Create","Area")">Registra Area</a></li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/Prueba/Index">
                        <span class="glyphicon glyphicon-user" aria-hidden="true">
                        </span> Iniciar Sesión</a></li>
                </ul>

            </div>
        </div>
    </nav>
   
     <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="pull-right"><a href="#">Subir</a></p>
            <!-- <p>&copy; 2013 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p> -->

            <div class="container text-center">
                <br />
                <h6>
                    <span style="color: black;">
                        <script type="text/javascript">

                            //<![CDATA[
                            var date = new Date();
                            var d = date.getDate();
                            var day = (d < 10) ? '0' + d : d;
                            var m = date.getMonth() + 1;
                            var month = (m < 10) ? '0' + m : m;
                            var yy = date.getYear();
                            var year = (yy < 1000) ? yy + 1900 : yy;
                            document.write('Software de Almacén e Inventarios "Rondesa" - Copyright information<br /><br />Cajamarca -  ' + day + "/" + month + "/" + year);
                            //]]>

                        </script>
                    </span>
                </h6>
            </div>  
            
        </footer>
    </div>

       

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>