AlinWebSystem/Controllers/BienesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Entities;
using Repository;
using Interfaces;
using Validator.BienesValidator;


namespace AlinWebSystem.Controllers
{
    public class BienesController : Controller
    {
        private InterfaceBien repoBienes;
        private InterfaceProducto repoProducto;
        private InterfaceAgencia repoAgencia;
        private InterfaceArea repoArea;
        private BienesValidator validator;
        private InterfaceDepreciacion repoDepreciacion;

        public BienesController(InterfaceBien repoBienes, InterfaceProducto repoProducto, InterfaceAgencia repoAgencia, InterfaceArea repoArea, BienesValidator validator, InterfaceDepreciacion repoDepreciacion)
        {
            this.repoBienes = repoBienes;
            this.repoProducto = repoProducto;
            this.repoAgencia = repoAgencia;
            this.repoArea = repoArea;
            this.repoDepreciacion = repoDepreciacion;
            this.validator = validator;
        }

        private void TableProductosYAgencia()
        {
           
            var agencia = repoAgencia.All();
            ViewData["IdAgencia"] = new SelectList(agencia, "IdAgencia", "Nombre");

            var area = repoArea.AllArea("");
            ViewData["IdAreafk"] = new SelectList(area, "IdArea", "Nombre");

            var depreciacion = repoDepreciacion.AllDepreciacion("");
            ViewData["IdDepreciacionFk"] = new SelectList(depreciacion, "IdDepreciacion", "Descripcion");

        }

        [HttpGet]
        public ViewResult Index(string query = "", DateTime? fecha1= null, DateTime? fecha2= null)
        {
            TableProductosYAgencia();
            var datos = repoBienes.GetBienesByfechas(query, fecha1, fecha2);
            
            return View("ListaDeBienes", datos);
        }

        [HttpGet]
        public ViewResult Create(string TipoDeProducto)
        {
            TableProductosYAgencia();
            if (TipoDeProducto == "Muebles")
            {
                return View("RegistroDeMuebles");
            }
            else if (TipoDeProducto == "Computo")
            {
                return View("RegistrarProducComputo");
            }
            else if (TipoDeProducto == "Vehiculos")
            {
                return View("RegistroDeVehiculos");
            }else
            {
                return View("RegistrarOtrosBienes");
            }
          
        }

        [HttpPost]
        public ActionResult Create(Bienes bienes, string TipoDeProducto)
        {
            validator.Execute(bienes);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));

            string segundaParteCodigo = "";

            if (TipoDeProducto == "Muebles")
            {
                if (ModelState.IsValid)
                {
                    var bienesBD = repoBienes.ObtenerBienesDeUnTipoEspecifico("Muebles");
                    if (bienesBD == null || bienesBD.Count() == 0)
                    {
                        segundaParteCodigo = segundaParteCodigo + "01";
                    }
                    else
                    {
                        Bienes bien = bienesBD.Last();
                        int n = bien.CodigoGrupo.Length;
                        string ultimoNro = bien.CodigoGrupo[n - 2] + "" + bien.CodigoGrupo[n - 1] + "";

                        int siguienteNro = int.Parse(ultimoNro) + 1;

                        string siguienteNroString = siguienteNro.ToString();
                        int newN = siguienteNroString.Length;
                        if (newN == 1)
                        {

                            siguienteNroString = "0" + siguienteNroString;
                        }
                        segundaParteCodigo = siguienteNroString;
                    }

                    repoBienes.Store(bienes);

                    string codigo = bienes.Grupo + "-" + segundaParteCodigo;
                    bienes.CodigoGrupo = codigo;

                    repoBienes.Update(bienes);
                    TempData["UpdateSuccess"] = "Se Guardo Correctamente";
                    return RedirectToAction("Index");
                }
                TableProductosYAgencia();
                return View("RegistroDeMuebles", bienes);
            //return View("ListaDeBienes", bienes);
                //iva aca el first return  
            //return View("RegistrarBienes", bienes);
            }
            else if (TipoDeProducto == "Computo")
            {
                if (ModelState.IsValid)
                {
                    var bienesBD = repoBienes.ObtenerBienesDeUnTipoEspecifico("Computo");
                    if (bienesBD == null || bienesBD.Count() == 0)
                    {
                        segundaParteCodigo = segundaParteCodigo + "01";
                    }
                    else
                    {
                        Bienes bien = bienesBD.Last();
                        int n = bien.CodigoGrupo.Length;
                        string ultimoNro = bien.CodigoGrupo[n - 2] + "" + bien.CodigoGrupo[n - 1] + "";

                        int siguienteNro = int.Parse(ultimoNro) + 1;

                        string siguienteNroString = siguienteNro.ToString();
                        int newN = siguienteNroString.Length;
                        if (newN == 1)
                        {

                            siguienteNroString = "0" + siguienteNroString;
                        }
                        segundaParteCodigo = siguienteNroString;
                    }

                    repoBienes.Store(bienes); 
                  

                    string codigo = bienes.Grupo + "-" + segundaParteCodigo;
                    bienes.CodigoGrupo = codigo;

                    repoBienes.Update(bienes);
                    TempData["UpdateSuccess"] = "Se Guardo Correctamente";
                    return RedirectToAction("Index");
                }
                TableProductosYAgencia();

                return View("RegistrarProducComputo", bienes);
            }
            else if (TipoDeProducto == "Vehiculos")
            {
                if (ModelState.IsValid)
                {
                    var bienesBD = repoBienes.ObtenerBienesDeUnTipoEspecifico("Vehiculos");
                    if (bienesBD == null || bienesBD.Count() == 0)
                    {
                        segundaParteCodigo = segundaParteCodigo + "01";
                    }
                    else
                    {
                        Bienes bien = bienesBD.Last();
                        int n = bien.CodigoGrupo.Length;
                        string ultimoNro = bien.CodigoGrupo[n - 2] + "" + bien.CodigoGrupo[n - 1] + "";

                        int siguienteNro = int.Parse(ultimoNro) + 1;

                        string siguienteNroString = siguienteNro.ToString();
                        int newN = siguienteNroString.Length;
                        if (newN == 1)
                        {

                            siguienteNroString = "0" + siguienteNroString;
                        }
                        segundaParteCodigo = siguienteNroString;
                    }

                    repoBienes.Store(bienes);

                    string codigo = bienes.Grupo + "-" + segundaParteCodigo;

                    bienes.CodigoGrupo = codigo;

                    repoBienes.Update(bienes);
                    TempData["UpdateSuccess"] = "Se Guardo Correctamente";
                    return RedirectToAction("Index");
                }
                TableProductosYAgencia();

                return View("RegistroDeVehiculos", bienes);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var bienesBD = repoBienes.ObtenerBienesDeUnTipoEspecifico("Otros");
                    if (bienesBD == null || bienesBD.Count() == 0)
                    {
                        segundaParteCodigo = segundaParteCodigo + "01";
                    }
                    else
                    {
                        Bienes bien = bienesBD.Last();
                        int n = bien.CodigoGrupo.Length;
                        string ultimoNro = bien.CodigoGrupo[n - 2] + "" + bien.CodigoGrupo[n - 1] + "";

                        int siguienteNro = int.Parse(ultimoNro) + 1;

                        string siguienteNroString = siguienteNro.ToString();
                        int newN = siguienteNroString.Length;
                        if (newN == 1)
                        {

                            siguienteNroString = "0" + siguienteNroString;
                        }
                        segundaParteCodigo = siguienteNroString;
                    }

                    repoBienes.Store(bienes);

                    string codigo = bienes.Grupo + "-" + segundaParteCodigo;
                    bienes.CodigoGrupo = codigo;

                    repoBienes.Update(bienes);
                    TempData["UpdateSuccess"] = "Se Guardo Correctamente";
                    return RedirectToAction("Index");
                }

                TableProductosYAgencia();

                return View("RegistroDeVehiculos", bienes);
            }

        }

        [HttpGet]
        public ViewResult Edit(Int32 id)
        {
            var data = repoBienes.Find(id);

           
            var agencia = repoAgencia.All();
            ViewData["IdAgencia"] = new SelectList(agencia, "IdAgencia", "Nombre", data.IdAgencia);

            var area = repoArea.AllArea("");
            ViewData["IdAreafk"] = new SelectList(area, "IdArea", "Nombre", data.IdAreafk);

            var depreciacion = repoDepreciacion.AllDepreciacion("");
            ViewData["IdDepreciacionFk"] = new SelectList(depreciacion, "IdDepreciacion", "Porcentaje");


            return View("EditarTipoBieMuebles", data);

AlinWebSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlinWebSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AlinWebSystem/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

//Importamos
using Interfaces;
using Entities;
using Validator.ProductoValidators;

namespace AlinWebSystem.Controllers
{
    public class ProductoController : Controller
    {
        //
        // GET: /Postulante/
        private InterfaceProducto repository;

        private ProductoValidators validator;
        //private string proveedor;




        public ProductoController(InterfaceProducto repository, ProductoValidators validator)
        {
            this.repository = repository;
            this.validator = validator;

        }



        [HttpGet]
        public ViewResult Index(string query = "", DateTime? fecha1 = null, DateTime? fecha2 = null)
        {
            // TraerProveedor();
            var datos = repository.ByQueryNameMoreDate(query, fecha1, fecha2);
            return View("ListaProductos", datos);
        }

        [HttpGet]
        public ViewResult Create(string TipoDeProducto)
        {
            
            //TraerProveedor();
            if (TipoDeProducto == "Suministros")
            {
                return View("RegistrarSuministros");
            }
            else if (TipoDeProducto == "Vestuario")
            {
                return View("RegistrarVestuarios");
            }
            else
            {
                return View("RegistrarOtros");
            }
        }

        [HttpPost]
        public ActionResult Create(Producto producto, string TipoDeProducto)
        {
            validator.Execute(producto);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));

            if (TipoDeProducto == "Suministros")
            {
                //validator.Execute(producto);
                //validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));
                if (ModelState.IsValid)
                {
                    repository.Store(producto);
                    TempData["UpdateSuccess"] = "Se Guardo Correctamente";
                    return RedirectToAction("Index");
                }

                return View("RegistrarSuministros", producto);
            }

            else if (TipoDeProducto == "Vestuario")
            {
                //validator.Execute(producto);
                //validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));
                if (ModelState.IsValid)
                {
                    repository.Store(producto);
                    TempData["UpdateSuccess"] = "Se Guardo Correctamente";
                    return RedirectToAction("Index");
                }

                return View("RegistrarVestuarios", producto);

            }
            else
            {
                //validator.Execute(producto);
                //validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));
                if (ModelState.IsValid)
                {
                    repository.Store(producto);
                    TempData["UpdateSuccess"] = "Se Guardo Correctamente";
                    return RedirectToAction("Index");
                }
                return View("RegistrarOtros", producto);
            }


            //if (ModelState.IsValid)
            //{
            //    repository.Store(producto);
            //    TempData["UpdateSuccess"] = "Se Guardo Correctamente";
            //    return RedirectToAction("Index");
            //}

            //return View("RegistrarSuministros", producto);
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            var data = repository.Find(id);
            return View("EditarProducto", data);
        }

        [HttpPost]
        public ActionResult Edit(Producto producto)
        {
            repository.Update(producto);
            TempData["UpdateSuccess"] = "Se Actualizó Correctamente";
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            repository.Delete(id);
            TempData["UpdateSuccess"] = "Se Eliminó Correctamente";
            return RedirectToAction("Index");
        }

    }
}

AlinWebSystem/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

//Importamos
using Interfaces;
using Entities;
using Validator.ProveedorValidators;

namespace AlinWebSystem.Controllers
{
    public class ProveedorController : Controller
    {
        private InterfaceProveedor repository;
        private ProveedorValidators validator;

        public ProveedorController(InterfaceProveedor repository, ProveedorValidators validator)
        {
            this.repository = repository;
            this.validator = validator;
        }

        [HttpGet]
        public ViewResult Index(string query = "")
        {
            var datos = repository.ByQueryAll(query);
            return View("ListaProveedores", datos);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View("RegistrarProveedor");
        }

        [HttpPost]
        public ActionResult Create(Proveedor proveedor)
        {
            validator.Execute(proveedor);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));

            if (ModelState.IsValid)
            {
                repository.Store(proveedor);

                TempData["UpdateSuccess"] = "Se Guardo Correctamente";

                return RedirectToAction("Index");
            }

            return View("RegistrarProveedor", proveedor);
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            var data = repository.Find(id);
            return View("EditarProveedor", data);
        }

        [HttpPost]
        public ActionResult Edit(Proveedor proveedor)
        {
            validator.Execute(proveedor);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));
            if (ModelState.IsValid)
            {
                repository.Update(proveedor);
                TempData["UpdateSuccess"] = "Se Actualizó Correctamente";
                return RedirectToAction("Index");
            }
            return View("EditarProveedor",proveedor);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            repository.Delete(id);
            TempData["UpdateSuccess"] = "Se Eliminó Correctamente";
            return RedirectToAction("Index");
        }
    }
}

AlinWebSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AlinWebSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AlinWebSystem/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    AlinWebSystem <small>Sistema de Gestión de “Almacén e Inventarios”</small>
                </h1>
                <ol class="breadcrumb">
                    <li class="active">
                        <i class="fa fa-dashboard"></i> Menú Principal
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <i class="fa fa-info-circle"></i>  <strong>Bienvenido a AlinWebSystem</strong> Creado por Carlos Chávez y Andres Chegne
                </div>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-users fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">Proveedores</div>
                                @*<div>Proveedores</div>*@
                            </div>
                        </div>
                    </div>
                    <a href="@Url.Action("Index", "Proveedor")">
                        <div class="panel-footer">
                            <span class="pull-left">Acceder</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-cubes fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">Almacén</div>
                                @*<div>Productos</div>*@
                            </div>
                        </div>
                    </div>
                    <a href="@Url.Action("Index", "Producto")">
                        <div class="panel-footer">
                            <span class="pull-left">Acceder</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-shopping-cart fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">Inventario</div>
                                @*<div>Ventas</div>*@
                            </div>
                        </div>
                    </div>
                    <a href="@Url.Action("Index","Bienes")">
                        <div class="panel-footer">
                            <span class="pull-left">Acceder</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>

            <!-- /.row -->

            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i>Software exclusivo:</h3>
                        </div>
                        <div class="panel-body">
                            @*<img src="/Image/ronde.png" class="img-responsive ronde" alt="Cinque Terre" >*@
                            <div class="container text-center">
                                <img src="@Url.Action("ronde.png", "Image")" class="img-thumbnail " alt="Cinque Terre">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->

            <div class="row">
                <div class="col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-long-arrow-right fa-fw"></i> Localización</h3>
                        </div>
                        <div class="panel-body">
                            <div id="morris-donut-chart"></div>
                            <div class="text-right">
                                @*<img src="/Image/ubironde.jpg" class="img-responsive" alt="Cinque Terre">*@
                                @*--MAPA--*@
                                <script src="http://maps.googleapis.com/maps/api/js">
                                </script>
                                <script>
                                    var posicion = new google.maps.LatLng(-7.1443147, -78.5146088); //POSICION

                                    function initialize() //Funcion que inicializa el mapa
                                    {
                                        var mapProp = {  //parametros del mapa
                                            center: posicion,
                                            zoom: 16,
                                            mapTypeId: google.maps.MapTypeId.ROADMAP
                                        };
                                        var map = new google.maps.Map(document.getElementById("mapa"), mapProp); //creacion del mapa

                                        var marker = new google.maps.Marker({ //para agregar el marcador al mapa
                                            position: posicion,
                                        });

                                        marker.setMap(map);

                                    }

                                    google.maps.event.addDomListener(window, 'load', initialize); //carga la funcion al abrir la pagina web
                                </script>
                                <div id="mapa" style="width: 300px; height: 300px; ">
                                </div>
                                @*--FIN DEL MAPA--*@
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i> Nuestro equipo de trabajo</h3>
                        </div>
                        <div class="panel-body">
                            <div class="list-group">
                                <a href="#" class="list-group-item">
                                    <span class="badge">Desarrollador</span>
                                    <i class="fa fa-fw fa-user"></i> Andrés Chegne Chávez
                                </a>
                                <a href="#" class="list-group-item">
                                    <span class="badge">Desarrollador</span>
                                    <i class="fa fa-fw fa-user"></i> Carlos Chávez Hinostroza
                                </a>
                                <a href="#" class="list-group-item">
                                    <span class="badge">Apoyo</span>
                                    <i class="fa fa-fw fa-user"></i> Anthony Torres Vargas
                                </a>
                               

                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-money fa-fw"></i>Contacto</h3>
                        </div>
                        <div class="panel-body">
                            <p><b>Dirección:</b> Jirón El Bosque # 346</p>
                            <p> <b>Teléfono:</b>(076) 366143</p>
                            <p><b> Correo:</b> coopac@rondesa.com</p>
                            <p>  <b>Facebook:</b> <a href="https://www.facebook.com/coopac.rondesa">Coopac Rondesa</a> </p>
                           
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->